"""
Тексты сюрвейерского акта (лёгкая версия, ТЗ 2.0 от 29.09.2026) на трёх языках: ru, uz (латиница), en.

Акт собирает сервер по шаблонам из структурированных данных — поэтому цифры в тексте всегда
совпадают с расчётом. Здесь только слова; числа подставляются через money() и pct().
Термины — по docs/Терминология — ru-uz-en.md (sugʻurta summasi, sugʻurta mukofoti, franshiza, anderrayter).
"""
LANGS = ("ru", "uz", "en")
NBSP = " "


def lang_of(lang) -> str:
    base = str(lang or "").strip().lower().replace("_", "-").split("-")[0]
    return base if base in LANGS else "ru"


def _num(x: float, lang: str, digits: int = 0) -> str:
    s = f"{x:,.{digits}f}"
    if lang == "en":
        return s
    # ru/uz: разряды неразрывным пробелом, дробная часть через запятую
    return s.replace(",", "\x00").replace(".", ",").replace("\x00", NBSP)


def money(x, lang: str = "ru") -> str:
    if x is None:
        return t("na", lang)
    cur = {"ru": "сум", "uz": "soʻm", "en": "UZS"}[lang_of(lang)]
    return _num(round(float(x)), lang_of(lang)) + NBSP + cur


def pct(x, lang: str = "ru", max_digits: int = 4) -> str:
    """Процент без лишних нулей, но не меньше двух знаков: 0,35 %, 1,5185 %, 20 % (целые — без дроби)."""
    if x is None:
        return t("na", lang)
    lang = lang_of(lang)
    v = round(float(x), max_digits)
    if v == int(v):
        s = str(int(v))
    else:
        s = f"{v:.{max_digits}f}".rstrip("0")
        if len(s.split(".")[1]) < 2:
            s = f"{v:.2f}"
        if lang != "en":
            s = s.replace(".", ",")
    return s + ("%" if lang == "en" else NBSP + "%")


def t(key: str, lang: str = "ru", **kw) -> str:
    row = TX.get(key)
    if row is None:
        return key
    s = row.get(lang_of(lang)) or row["ru"]
    return s.format(**kw) if kw else s


def label(group: dict, code: str, lang: str) -> str:
    row = group.get(code)
    if row is None:
        return str(code)
    return row.get(lang_of(lang)) or row["ru"]


TX = {
    # ---------- шапка и подвал ----------
    "title": {"ru": "СЮРВЕЙЕРСКИЙ АКТ ПРЕДСТРАХОВОГО ОСМОТРА",
              "uz": "SUGʻURTADAN OLDINGI KOʻZDAN KECHIRISH BOʻYICHA SYURVEYER DALOLATNOMASI",
              "en": "SURVEYOR'S PRE-INSURANCE INSPECTION REPORT"},
    "insurer": {"ru": "Страховщик", "uz": "Sugʻurtalovchi", "en": "Insurer"},
    "date": {"ru": "Дата", "uz": "Sana", "en": "Date"},
    "number": {"ru": "Номер акта", "uz": "Dalolatnoma raqami", "en": "Report No."},
    "footer": {"ru": "Акт сформирован ИИ-сюрвейером, подлежит подтверждению андеррайтером",
               "uz": "Dalolatnoma sunʼiy intellekt syurveyeri tomonidan tuzilgan, anderrayter tasdigʻini talab qiladi",
               "en": "The report was generated by the AI surveyor and is subject to underwriter confirmation"},
    "page": {"ru": "Страница {i} из {n}", "uz": "{i}-sahifa, jami {n}", "en": "Page {i} of {n}"},
    "na": {"ru": "данные недоступны", "uz": "maʼlumot mavjud emas", "en": "data not available"},
    "no_inspection": {"ru": "осмотр не проводился", "uz": "koʻzdan kechirish oʻtkazilmagan",
                      "en": "inspection not carried out"},
    "check_mark": {"ru": "проверьте", "uz": "tekshiring", "en": "please check"},
    "uncalibrated": {"ru": "не калибровано", "uz": "kalibrlanmagan", "en": "not calibrated"},
    "expert": {"ru": "экспертная оговорка", "uz": "ekspert izohi", "en": "expert clause"},

    # ---------- разделы ----------
    "s1": {"ru": "Объект и идентификация", "uz": "Obyekt va uni identifikatsiya qilish",
           "en": "Object and identification"},
    "s2": {"ru": "Результаты осмотра", "uz": "Koʻzdan kechirish natijalari", "en": "Inspection results"},
    "s3": {"ru": "Стоимость и страховая сумма", "uz": "Qiymat va sugʻurta summasi", "en": "Value and sum insured"},
    "s4": {"ru": "Риск-факторы и франшиза", "uz": "Xavf omillari va franshiza", "en": "Risk factors and deductible"},
    "s5": {"ru": "Заключение и рекомендация", "uz": "Xulosa va tavsiya", "en": "Conclusion and recommendation"},

    # ---------- раздел 1 ----------
    "class": {"ru": "Класс страхования", "uz": "Sugʻurta klassi", "en": "Insurance class"},
    "product": {"ru": "Продукт", "uz": "Mahsulot", "en": "Product"},
    "region": {"ru": "Регион", "uz": "Hudud", "en": "Region"},
    "guard": {"ru": "Охрана", "uz": "Qoʻriqlash", "en": "Security"},
    "yes": {"ru": "есть", "uz": "bor", "en": "yes"},
    "no": {"ru": "нет", "uz": "yoʻq", "en": "no"},
    "also_in": {"ru": "также: {what}", "uz": "shuningdek: {what}", "en": "also: {what}"},

    # ---------- раздел 2 ----------
    "views_seen": {"ru": "Осмотрено по фото", "uz": "Suratlar boʻyicha koʻrilgan",
                   "en": "Inspected on photos"},
    "views_missing": {"ru": "Не хватает ракурсов", "uz": "Yetishmayotgan rakurslar", "en": "Missing views"},
    "views_all": {"ru": "все нужные ракурсы представлены", "uz": "barcha kerakli rakurslar taqdim etilgan",
                  "en": "all required views provided"},
    "views_none_needed": {"ru": "для этого класса ракурсы не требуются",
                          "uz": "bu klass uchun rakurslar talab qilinmaydi",
                          "en": "no views are required for this class"},
    "damages": {"ru": "Видимые повреждения", "uz": "Koʻrinadigan shikastlar", "en": "Visible damage"},
    "damages_none": {"ru": "на представленных фото не обнаружены",
                     "uz": "taqdim etilgan suratlarda aniqlanmadi",
                     "en": "none found on the photos provided"},
    "documents": {"ru": "Документы на объект", "uz": "Obyekt hujjatlari", "en": "Object documents"},
    "docs_given": {"ru": "представлены", "uz": "taqdim etilgan", "en": "provided"},
    "docs_not_given": {"ru": "не представлены", "uz": "taqdim etilmagan", "en": "not provided"},
    "files_count": {"ru": "Загружено файлов", "uz": "Yuklangan fayllar", "en": "Files uploaded"},
    "p_no_photos": {"ru": "Осмотр не проводился: фотографии объекта не загружены. Разделы об осмотре заполнены "
                          "только по вводу сотрудника.",
                    "uz": "Koʻzdan kechirish oʻtkazilmagan: obyekt suratlari yuklanmagan. Koʻzdan kechirish "
                          "boʻlimlari faqat xodim kiritgan maʼlumotlar asosida toʻldirilgan.",
                    "en": "Inspection not carried out: no photos of the object were uploaded. The inspection "
                          "sections are based only on the data entered by staff."},
    "p_ai_failed": {"ru": "Фотографии загружены (файлов: {n}), но распознать их не удалось: {reason}. Осмотр по фото "
                          "не проводился — объект нужно проверить вручную.",
                    "uz": "Suratlar yuklandi (fayllar: {n}), lekin ularni aniqlab boʻlmadi: {reason}. Suratlar boʻyicha "
                          "koʻzdan kechirish oʻtkazilmagan — obyektni qoʻlda tekshirish kerak.",
                    "en": "Photos were uploaded (files: {n}) but could not be recognised: {reason}. No photo inspection "
                          "was carried out — the object must be checked manually."},
    "p_inspected": {"ru": "Осмотр проведён по фотографиям и снимкам документов (файлов: {n}). Распознанные "
                          "значения требуют проверки по оригиналам.",
                    "uz": "Koʻzdan kechirish suratlar va hujjat suratlari boʻyicha oʻtkazildi (fayllar: {n}). "
                          "Aniqlangan qiymatlar asl nusxalar bilan tekshirilishi kerak.",
                    "en": "The inspection was carried out on photos and document images (files: {n}). Recognised "
                          "values must be checked against the originals."},

    # ---------- раздел 3 ----------
    "sum_insured": {"ru": "Страховая сумма", "uz": "Sugʻurta summasi", "en": "Sum insured"},
    "object_value": {"ru": "Стоимость объекта", "uz": "Obyekt qiymati", "en": "Object value"},
    "ratio": {"ru": "Отношение суммы к стоимости", "uz": "Summaning qiymatga nisbati",
              "en": "Sum insured to value"},
    "verdict": {"ru": "Вывод", "uz": "Xulosa", "en": "Conclusion"},
    "v_normal": {"ru": "В норме: страховая сумма составляет {ratio} стоимости объекта.",
                 "uz": "Meʼyorda: sugʻurta summasi obyekt qiymatining {ratio} qismini tashkil etadi.",
                 "en": "Within norm: the sum insured is {ratio} of the object value."},
    "v_under": {"ru": "Недострахование: страховая сумма составляет {ratio} стоимости, выплата будет "
                      "пропорциональной — в той же доле от ущерба ({ref}).",
                "uz": "Toʻliq boʻlmagan mulkiy sugʻurta: sugʻurta summasi qiymatning {ratio} qismini tashkil "
                      "etadi, toʻlov zararning xuddi shu ulushida mutanosib boʻladi ({ref}).",
                "en": "Underinsurance: the sum insured is {ratio} of the value; claims will be paid "
                      "proportionally, in the same share of the loss ({ref})."},
    "v_under_small": {"ru": "Страховая сумма ниже стоимости ({ratio}) в пределах допустимого; при убытке выплата "
                            "будет в той же доле ({ref}).",
                      "uz": "Sugʻurta summasi qiymatdan past ({ratio}), lekin ruxsat etilgan chegarada; zarar "
                            "yuz berganda toʻlov xuddi shu ulushda boʻladi ({ref}).",
                      "en": "The sum insured is below the value ({ratio}) but within the acceptable range; "
                            "a claim will be paid in the same share ({ref})."},
    "v_over": {"ru": "Превышение: страховая сумма выше стоимости на {diff}. Сумму нужно снизить до стоимости — "
                     "в части превышения договор недействителен ({ref}).",
               "uz": "Oshib ketish: sugʻurta summasi qiymatdan {diff} ga yuqori. Summani qiymatgacha kamaytirish "
                     "kerak — oshgan qismda shartnoma haqiqiy emas ({ref}).",
               "en": "Over-insurance: the sum insured exceeds the value by {diff}. The sum must be reduced to "
                     "the value — the contract is void in the excess part ({ref})."},
    "depreciated": {"ru": "Стоимость с учётом износа (ориентир)", "uz": "Eskirishni hisobga olgan qiymat (moʻljal)",
                    "en": "Depreciated value (guide)"},
    "depr_how": {"ru": "цена {price} минус износ {rate} в год × {years} лет",
                 "uz": "narx {price}, yiliga {rate} eskirish × {years} yil",
                 "en": "price {price} less wear {rate} per year × {years} years"},
    "depr_note": {"ru": "Ориентир, а не оценка: стоимость объекта вводит сотрудник.",
                  "uz": "Bu baholash emas, faqat moʻljal: obyekt qiymatini xodim kiritadi.",
                  "en": "A guide, not a valuation: the object value is entered by staff."},

    # ---------- раздел 4 ----------
    "level": {"ru": "Уровень риска", "uz": "Xavf darajasi", "en": "Risk level"},
    "factors": {"ru": "Признаки", "uz": "Belgilar", "en": "Indicators"},
    "base_rate": {"ru": "Базовая ставка", "uz": "Bazaviy tarif", "en": "Base rate"},
    "adj": {"ru": "Поправка по уровню риска", "uz": "Xavf darajasi boʻyicha tuzatish", "en": "Risk level loading"},
    "applied_rate": {"ru": "Рекомендуемый тариф", "uz": "Tavsiya etilgan tarif", "en": "Recommended rate"},
    "min_rate": {"ru": "Минимальная ставка продукта", "uz": "Mahsulotning eng kam tarifi",
                 "en": "Product minimum rate"},
    "premium": {"ru": "Страховая премия", "uz": "Sugʻurta mukofoti", "en": "Premium"},
    "premium_term": {"ru": "за {days} дн.", "uz": "{days} kun uchun", "en": "for {days} days"},
    "franchise": {"ru": "Франшиза", "uz": "Franshiza", "en": "Deductible"},
    "clauses": {"ru": "Оговорки", "uz": "Izohlar (shartlar)", "en": "Clauses"},
    "rate_undefined": {"ru": "ставка не определена — нужен расчёт андеррайтера",
                       "uz": "tarif aniqlanmagan — anderrayter hisobi kerak",
                       "en": "rate not determined — underwriter calculation required"},
    "rate_by_act": {"ru": "по нормативному акту, без поправок", "uz": "meʼyoriy hujjat boʻyicha, tuzatishsiz",
                    "en": "per the statutory act, no loadings"},
    "adj_none_statutory": {"ru": "не применяется (обязательный вид)", "uz": "qoʻllanilmaydi (majburiy tur)",
                           "en": "not applied (compulsory class)"},
    "min_applied": {"ru": "применена минимальная ставка продукта", "uz": "mahsulotning eng kam tarifi qoʻllanildi",
                    "en": "product minimum rate applied"},

    # ---------- уровень риска: признаки ----------
    "f_cond_damage": {"ru": "Состояние объекта: видимые повреждения ({n}) — повышает риск",
                      "uz": "Obyekt holati: koʻrinadigan shikastlar ({n}) — xavfni oshiradi",
                      "en": "Condition: visible damage ({n}) — increases risk"},
    "f_cond_worn": {"ru": "Состояние объекта: признаки износа — повышает риск",
                    "uz": "Obyekt holati: eskirish belgilari — xavfni oshiradi",
                    "en": "Condition: signs of wear — increases risk"},
    "f_cond_new": {"ru": "Состояние объекта: объект новый ({year}), повреждений на фото нет — снижает риск",
                   "uz": "Obyekt holati: obyekt yangi ({year}), suratlarda shikast yoʻq — xavfni kamaytiradi",
                   "en": "Condition: new object ({year}), no damage on photos — reduces risk"},
    "f_cond_neutral": {"ru": "Состояние объекта: повреждений на фото нет, объект не новый — не влияет",
                       "uz": "Obyekt holati: suratlarda shikast yoʻq, obyekt yangi emas — taʼsir qilmaydi",
                       "en": "Condition: no damage on photos, object not new — no effect"},
    "f_cond_no_year": {"ru": "Состояние объекта: повреждений на фото нет, год выпуска неизвестен — не влияет",
                       "uz": "Obyekt holati: suratlarda shikast yoʻq, ishlab chiqarilgan yili nomaʼlum — taʼsir qilmaydi",
                       "en": "Condition: no damage on photos, year of manufacture unknown — no effect"},
    "f_cond_unknown": {"ru": "Состояние объекта: не оценено — нет фото и сведений",
                       "uz": "Obyekt holati: baholanmagan — surat va maʼlumot yoʻq",
                       "en": "Condition: not assessed — no photos or data"},
    "f_loc_up": {"ru": "Место эксплуатации: {place} — повышает риск",
                 "uz": "Foydalanish joyi: {place} — xavfni oshiradi",
                 "en": "Place of operation: {place} — increases risk"},
    "f_loc_down": {"ru": "Место эксплуатации: {place} — снижает риск",
                   "uz": "Foydalanish joyi: {place} — xavfni kamaytiradi",
                   "en": "Place of operation: {place} — reduces risk"},
    "f_loc_guarded_open": {"ru": "Место эксплуатации: {place}, но под охраной — не влияет",
                           "uz": "Foydalanish joyi: {place}, lekin qoʻriqlanadi — taʼsir qilmaydi",
                           "en": "Place of operation: {place}, but guarded — no effect"},
    "f_loc_neutral": {"ru": "Место эксплуатации: {place} — не влияет",
                      "uz": "Foydalanish joyi: {place} — taʼsir qilmaydi",
                      "en": "Place of operation: {place} — no effect"},
    "f_loc_unknown": {"ru": "Место эксплуатации: не указано", "uz": "Foydalanish joyi: koʻrsatilmagan",
                      "en": "Place of operation: not stated"},
    "f_loss_up": {"ru": "История убытков: {n} за три года — повышает риск",
                  "uz": "Zararlar tarixi: uch yilda {n} ta — xavfni oshiradi",
                  "en": "Loss history: {n} in three years — increases risk"},
    "f_loss_down": {"ru": "История убытков: убытков за три года нет — снижает риск",
                    "uz": "Zararlar tarixi: uch yilda zarar boʻlmagan — xavfni kamaytiradi",
                    "en": "Loss history: no losses in three years — reduces risk"},
    "f_loss_neutral": {"ru": "История убытков: {n} за три года — не влияет",
                       "uz": "Zararlar tarixi: uch yilda {n} ta — taʼsir qilmaydi",
                       "en": "Loss history: {n} in three years — no effect"},
    "f_loss_unknown": {"ru": "История убытков: сведений нет", "uz": "Zararlar tarixi: maʼlumot yoʻq",
                       "en": "Loss history: no data"},
    "f_docs_down": {"ru": "Документы на объект представлены — снижает риск",
                    "uz": "Obyekt hujjatlari taqdim etilgan — xavfni kamaytiradi",
                    "en": "Object documents provided — reduces risk"},
    "f_docs_up": {"ru": "Документы на объект не представлены — повышает риск",
                  "uz": "Obyekt hujjatlari taqdim etilmagan — xavfni oshiradi",
                  "en": "Object documents not provided — increases risk"},
    "level_rule": {"ru": "Правило: признак, повышающий риск, даёт +1, снижающий — −1. Сумма {net}: не больше "
                         "{low} — низкий уровень, не меньше {high} — высокий, иначе умеренный. Если известно "
                         "меньше {k} признаков — умеренный. Пороги экспертные, не калибровано.",
                   "uz": "Qoida: xavfni oshiruvchi belgi +1, kamaytiruvchi −1 beradi. Yigʻindi {net}: {low} dan "
                         "oshmasa — past daraja, {high} dan kam boʻlmasa — yuqori, aks holda oʻrtacha. Agar "
                         "{k} tadan kam belgi maʼlum boʻlsa — oʻrtacha. Chegaralar ekspert tomonidan belgilangan, "
                         "kalibrlanmagan.",
                   "en": "Rule: an indicator that increases risk counts +1, one that reduces it −1. Total {net}: "
                         "{low} or less — low, {high} or more — high, otherwise moderate. If fewer than {k} "
                         "indicators are known — moderate. Expert thresholds, not calibrated."},
    "level_few": {"ru": "Известно мало признаков — принят умеренный уровень",
                  "uz": "Belgilar kam maʼlum — oʻrtacha daraja qabul qilindi",
                  "en": "Few indicators known — moderate level assumed"},

    # ---------- ставка: как посчитана ----------
    "how_title": {"ru": "Как посчитан тариф", "uz": "Tarif qanday hisoblangan", "en": "How the rate was calculated"},
    "how_base_tech": {"ru": "Базовая ставка {base} — техническая ставка калькулятора по классу {cls}, тип «{otype}» "
                            "(базовые ставки и нагрузка из справочника, экспертные значения)",
                      "uz": "Bazaviy tarif {base} — kalkulyatorning {cls}-klass, «{otype}» turi boʻyicha texnik "
                            "tarifi (maʼlumotnomadagi bazaviy tariflar va yuklama, ekspert qiymatlari)",
                      "en": "Base rate {base} — the calculator's technical rate for class {cls}, type «{otype}» "
                            "(base rates and loading from the reference, expert values)"},
    "how_base_tech_avg": {"ru": "Базовая ставка {base} — техническая ставка калькулятора по классу {cls}; тип объекта "
                                "не определён, взята средняя базовая ставка класса",
                          "uz": "Bazaviy tarif {base} — kalkulyatorning {cls}-klass boʻyicha texnik tarifi; obyekt turi "
                                "aniqlanmagan, klassning oʻrtacha bazaviy tarifi olindi",
                          "en": "Base rate {base} — the calculator's technical rate for class {cls}; the object type "
                                "was not determined, the class average base rate was used"},
    "how_base_product": {"ru": "Базовая ставка {base} — ставка продукта {code} по тарифной политике",
                         "uz": "Bazaviy tarif {base} — tarif siyosati boʻyicha {code} mahsuloti tarifi",
                         "en": "Base rate {base} — product {code} rate under the tariff policy"},
    "how_adj": {"ru": "Поправка по уровню риска «{level}»: +{adj} (не калибровано)",
                "uz": "«{level}» xavf darajasi boʻyicha tuzatish: +{adj} (kalibrlanmagan)",
                "en": "Risk level «{level}» loading: +{adj} (not calibrated)"},
    "how_min_ok": {"ru": "Ставка не ниже минимальной ставки продукта {min}",
                   "uz": "Tarif mahsulotning eng kam tarifi {min} dan past emas",
                   "en": "The rate is not below the product minimum {min}"},
    "how_min_applied": {"ru": "Расчётная ставка {calc} ниже минимальной — применена минимальная ставка продукта {min}",
                        "uz": "Hisoblangan tarif {calc} eng kamidan past — mahsulotning eng kam tarifi {min} qoʻllanildi",
                        "en": "The calculated rate {calc} is below the minimum — the product minimum {min} applied"},
    "how_min_none": {"ru": "Минимальная ставка продукта в справочнике не задана",
                     "uz": "Mahsulotning eng kam tarifi maʼlumotnomada belgilanmagan",
                     "en": "No product minimum rate in the reference"},
    "how_premium": {"ru": "Премия = {sum} × {rate} × {days} / 365 = {premium}",
                    "uz": "Mukofot = {sum} × {rate} × {days} / 365 = {premium}",
                    "en": "Premium = {sum} × {rate} × {days} / 365 = {premium}"},
    "how_undefined": {"ru": "У продукта {code} ставка «{rate_text}» — числа в справочнике нет, ставку определяет "
                            "андеррайтер. Цифры не подставлялись.",
                      "uz": "{code} mahsulotining tarifi «{rate_text}» — maʼlumotnomada son yoʻq, tarifni "
                            "anderrayter belgilaydi. Raqamlar qoʻyilmadi.",
                      "en": "Product {code} rate is «{rate_text}» — there is no number in the reference, the rate "
                            "is set by the underwriter. No figures were substituted."},
    "how_no_base": {"ru": "В справочнике нет базовой ставки для класса {cls} — ставку определяет андеррайтер",
                    "uz": "Maʼlumotnomada {cls}-klass uchun bazaviy tarif yoʻq — tarifni anderrayter belgilaydi",
                    "en": "No base rate for class {cls} in the reference — the rate is set by the underwriter"},
    "how_statutory": {"ru": "Обязательный вид: ставка {rate} по нормативному акту ({ref}), без поправок",
                      "uz": "Majburiy tur: tarif {rate} meʼyoriy hujjat boʻyicha ({ref}), tuzatishsiz",
                      "en": "Compulsory class: rate {rate} per the statutory act ({ref}), no loadings"},
    "how_statutory_na": {"ru": "Обязательный вид: ставка устанавливается нормативным актом ({ref}) и зависит от "
                               "условий акта — рассчитайте её в разделе «Обязательные виды»",
                         "uz": "Majburiy tur: tarif meʼyoriy hujjat ({ref}) bilan belgilanadi va uning shartlariga "
                               "bogʻliq — uni «Majburiy turlar» boʻlimida hisoblang",
                         "en": "Compulsory class: the rate is set by the statutory act ({ref}) and depends on its "
                               "terms — calculate it in the «Compulsory classes» section"},

    # ---------- франшиза ----------
    "fr_not_needed": {"ru": "Франшиза не требуется", "uz": "Franshiza talab qilinmaydi",
                      "en": "No deductible required"},
    "fr_statutory": {"ru": "Франшиза не применяется: обязательный вид страхования, условия по нормативному акту",
                     "uz": "Franshiza qoʻllanilmaydi: majburiy sugʻurta turi, shartlar meʼyoriy hujjat boʻyicha",
                     "en": "No deductible: compulsory class, terms per the statutory act"},
    "fr_advise_range": {"ru": "Рекомендуется рассмотреть безусловную франшизу {range} страховой суммы ({amount}). "
                              "Точный размер определяет андеррайтер.",
                        "uz": "Sugʻurta summasining {range} miqdorida shartsiz franshizani koʻrib chiqish tavsiya "
                              "etiladi ({amount}). Aniq miqdorni anderrayter belgilaydi.",
                        "en": "An unconditional deductible of {range} of the sum insured ({amount}) is recommended "
                              "for consideration. The exact amount is set by the underwriter."},
    "fr_advise_nosize": {"ru": "Рекомендуется рассмотреть франшизу, размер определяет андеррайтер",
                         "uz": "Franshizani koʻrib chiqish tavsiya etiladi, miqdorini anderrayter belgilaydi",
                         "en": "A deductible is recommended for consideration; the amount is set by the underwriter"},
    "fr_range_upto": {"ru": "до {to}", "uz": "{to} gacha", "en": "up to {to}"},
    "fr_range": {"ru": "от {from_} до {to}", "uz": "{from_} dan {to} gacha", "en": "from {from_} to {to}"},
    "fr_grounds": {"ru": "Основания", "uz": "Asoslar", "en": "Grounds"},
    "fr_g_small_losses": {"ru": "{n} мелких убытков за три года", "uz": "uch yilda {n} ta kichik zarar",
                          "en": "{n} small losses in three years"},
    "fr_g_level_high": {"ru": "высокий уровень риска", "uz": "yuqori xavf darajasi", "en": "high risk level"},
    "fr_g_dominant": {"ru": "явно преобладает один риск: {what}", "uz": "bitta xavf aniq ustun: {what}",
                      "en": "one risk clearly dominates: {what}"},
    "fr_g_client": {"ru": "клиент просит снизить премию", "uz": "mijoz mukofotni kamaytirishni soʻraydi",
                    "en": "the client asks to lower the premium"},
    "fr_none_grounds": {"ru": "оснований нет: мелких убытков меньше двух, уровень не высокий, преобладающего риска и "
                              "просьбы клиента нет",
                        "uz": "asoslar yoʻq: kichik zararlar ikkitadan kam, daraja yuqori emas, ustun xavf va mijoz "
                              "iltimosi yoʻq",
                        "en": "no grounds: fewer than two small losses, level not high, no dominant risk and no "
                              "client request"},
    "fr_alt": {"ru": "Вместо франшизы можно ограничиться оговорками ниже.",
               "uz": "Franshiza oʻrniga quyidagi izohlar bilan cheklanish mumkin.",
               "en": "Instead of a deductible, the clauses below may be used."},

    # ---------- раздел 5 ----------
    "d_accept": {"ru": "Рекомендация: принять объект на страхование.",
                 "uz": "Tavsiya: obyektni sugʻurtaga qabul qilish.",
                 "en": "Recommendation: accept the object for insurance."},
    "d_accept_with_clauses": {"ru": "Рекомендация: принять объект на страхование с оговорками.",
                              "uz": "Tavsiya: obyektni izohlar (shartlar) bilan sugʻurtaga qabul qilish.",
                              "en": "Recommendation: accept the object for insurance subject to clauses."},
    "d_decline": {"ru": "Рекомендация: отказать в страховании — сработали все признаки повышенного риска.",
                  "uz": "Tavsiya: sugʻurtadan rad etish — xavfni oshiruvchi barcha belgilar mavjud.",
                  "en": "Recommendation: decline — all risk-increasing indicators are present."},
    "disc_title": {"ru": "Расхождения в данных", "uz": "Maʼlumotlardagi tafovutlar", "en": "Data discrepancies"},
    "disc_none": {"ru": "Расхождений между источниками не выявлено.",
                  "uz": "Manbalar oʻrtasida tafovut aniqlanmadi.",
                  "en": "No discrepancies between sources were found."},
    "disc_line": {"ru": "{label}: {values}.", "uz": "{label}: {values}.", "en": "{label}: {values}."},
    "disc_priority": {"ru": "При расхождении приоритет у документа с печатью производителя; решение принимает "
                            "андеррайтер.",
                      "uz": "Tafovut boʻlsa, ishlab chiqaruvchi muhri qoʻyilgan hujjat ustuvor; qarorni "
                            "anderrayter qabul qiladi.",
                      "en": "In case of discrepancy the document bearing the manufacturer's seal prevails; the "
                            "underwriter decides."},
    "checks_title": {"ru": "Что проверить андеррайтеру до выдачи полиса",
                     "uz": "Polis berilishidan oldin anderrayter nimani tekshirishi kerak",
                     "en": "What the underwriter should check before issuing the policy"},
    "missing_title": {"ru": "Данные недоступны", "uz": "Maʼlumot mavjud emas", "en": "Data not available"},

    # ---------- что проверить ----------
    "c_disc": {"ru": "Снять расхождение «{label}» по оригиналу документа",
               "uz": "«{label}» boʻyicha tafovutni hujjat asl nusxasi orqali bartaraf etish",
               "en": "Resolve the «{label}» discrepancy against the original document"},
    "c_views": {"ru": "Запросить недостающие фото: {views}", "uz": "Yetishmayotgan suratlarni soʻrash: {views}",
                "en": "Request the missing photos: {views}"},
    "c_no_inspection": {"ru": "Провести осмотр: фотографии объекта не представлены",
                        "uz": "Koʻzdan kechirish oʻtkazish: obyekt suratlari taqdim etilmagan",
                        "en": "Carry out an inspection: no photos of the object were provided"},
    "c_ai_failed": {"ru": "Проверить объект по фото вручную: автоматическое распознавание не выполнено",
                    "uz": "Obyektni suratlar boʻyicha qoʻlda tekshirish: avtomatik aniqlash bajarilmadi",
                    "en": "Check the object on the photos manually: automatic recognition failed"},
    "c_under": {"ru": "Предупредить клиента о пропорциональной выплате или довести сумму до стоимости",
                "uz": "Mijozni mutanosib toʻlov haqida ogohlantirish yoki summani qiymatgacha yetkazish",
                "en": "Warn the client about proportional settlement or raise the sum to the value"},
    "c_over": {"ru": "Снизить страховую сумму до стоимости объекта",
               "uz": "Sugʻurta summasini obyekt qiymatigacha kamaytirish",
               "en": "Reduce the sum insured to the object value"},
    "c_rate_undefined": {"ru": "Определить ставку: в справочнике её нет",
                         "uz": "Tarifni belgilash: u maʼlumotnomada yoʻq",
                         "en": "Set the rate: it is not in the reference"},
    "c_statutory": {"ru": "Применить тариф нормативного акта без поправок",
                    "uz": "Meʼyoriy hujjat tarifini tuzatishsiz qoʻllash",
                    "en": "Apply the statutory tariff without loadings"},
    "c_franchise": {"ru": "Решить вопрос о франшизе и её размере", "uz": "Franshiza va uning miqdori masalasini hal qilish",
                    "en": "Decide on the deductible and its amount"},
    "c_damages": {"ru": "Оценить видимые повреждения и исключить их из покрытия",
                  "uz": "Koʻrinadigan shikastlarni baholash va ularni qoplamadan chiqarish",
                  "en": "Assess the visible damage and exclude it from cover"},
    "c_docs": {"ru": "Запросить документы на объект", "uz": "Obyekt hujjatlarini soʻrash",
               "en": "Request the object documents"},
    "c_missing": {"ru": "Уточнить: {what}", "uz": "Aniqlashtirish: {what}", "en": "Clarify: {what}"},
    "c_confirm": {"ru": "Сверить распознанные данные с оригиналами документов",
                  "uz": "Aniqlangan maʼlumotlarni hujjatlarning asl nusxalari bilan solishtirish",
                  "en": "Verify the recognised data against the original documents"},
    "c_decline": {"ru": "Подтвердить или пересмотреть отказ после проверки данных",
                  "uz": "Maʼlumotlar tekshirilgandan soʻng rad etishni tasdiqlash yoki qayta koʻrib chiqish",
                  "en": "Confirm or reconsider the decline after checking the data"},

    # ---------- /act/photos ----------
    "warn_pd": {"ru": "Не загружайте документы с данными людей (паспорт, ФИО, адрес): снимки уходят в языковую "
                      "модель как картинки. Сервер тестовый.",
                "uz": "Odamlar maʼlumotlari bor hujjatlarni (pasport, F.I.Sh., manzil) yuklamang: suratlar til "
                      "modeliga rasm sifatida yuboriladi. Server test rejimida.",
                "en": "Do not upload documents containing personal data (passport, names, addresses): images are "
                      "sent to the language model as pictures. This is a test server."},
    "ph_ok": {"ru": "Распознано по фото: {n} значений. Проверьте каждое — модель может ошибаться.",
              "uz": "Suratlardan aniqlandi: {n} ta qiymat. Har birini tekshiring — model xato qilishi mumkin.",
              "en": "Recognised from photos: {n} values. Check each one — the model can make mistakes."},
    "ph_empty": {"ru": "Модель не нашла на фото значений для акта. Заполните данные вручную.",
                 "uz": "Model suratlarda dalolatnoma uchun qiymat topmadi. Maʼlumotlarni qoʻlda kiriting.",
                 "en": "The model found no values for the report on the photos. Enter the data manually."},
    "ph_ai_off": {"ru": "Распознавание фото недоступно: {reason}. Фото сохранены; данные можно ввести вручную — акт "
                        "сформируется.",
                  "uz": "Suratlarni aniqlash imkonsiz: {reason}. Suratlar saqlandi; maʼlumotlarni qoʻlda kiritish "
                        "mumkin — dalolatnoma tuziladi.",
                  "en": "Photo recognition is unavailable: {reason}. Photos are saved; enter the data manually — "
                        "the report will still be generated."},
    "ph_bad_json": {"ru": "языковая модель вернула ответ не по схеме", "uz": "til modeli javobi sxemaga mos emas",
                    "en": "the language model returned an answer that does not match the schema"},
    "ph_format": {"ru": "формат не принимается — пришлите JPG, PNG или PDF (WEBP и HEIC приложение переводит в JPG "
                        "само)",
                  "uz": "format qabul qilinmaydi — JPG, PNG yoki PDF yuboring (WEBP va HEIC ilova oʻzi JPG ga "
                        "oʻtkazadi)",
                  "en": "format not accepted — send JPG, PNG or PDF (the app converts WEBP and HEIC to JPG itself)"},
    "ph_too_big": {"ru": "файл больше {mb} МБ", "uz": "fayl {mb} MB dan katta", "en": "file larger than {mb} MB"},    "ph_empty_file": {"ru": "пустой файл", "uz": "boʻsh fayl", "en": "empty file"},
    "ph_too_many": {"ru": "За один раз — не больше {n} файлов", "uz": "Bir martada {n} tadan koʻp fayl emas",
                    "en": "No more than {n} files at a time"},
    "ph_none": {"ru": "Файлы не приняты", "uz": "Fayllar qabul qilinmadi", "en": "No files accepted"},
    "ai_not_connected": {"ru": "языковая модель не подключена", "uz": "til modeli ulanmagan",
                         "en": "the language model is not connected"},
    "ai_no_files": {"ru": "текущая языковая модель не принимает изображения",
                    "uz": "joriy til modeli rasmlarni qabul qilmaydi",
                    "en": "the current language model does not accept images"},
    "not_found": {"ru": "Акт не найден или его срок (7 дней) истёк", "uz": "Dalolatnoma topilmadi yoki muddati (7 kun) tugagan",
                  "en": "Report not found or its 7-day retention period has expired"},
    "ph_body_too_big": {"ru": "Запрос больше {mb} МБ — отправьте меньше файлов или уменьшите снимки",
                        "uz": "Soʻrov {mb} MB dan katta — kamroq fayl yuboring yoki suratlarni kichraytiring",
                        "en": "The request is larger than {mb} MB — send fewer files or smaller images"},
    "ph_length_required": {"ru": "Не указан размер запроса — обновите приложение и повторите",
                           "uz": "Soʻrov hajmi koʻrsatilmagan — ilovani yangilang va qaytadan urinib koʻring",
                           "en": "Request size is missing — update the app and try again"},
    "ph_guest_limit": {"ru": "Слишком много фото подряд: без входа не больше {n} фото в час. Подождите немного и "
                             "повторите.",
                       "uz": "Juda koʻp surat: kirishsiz soatiga {n} tadan koʻp emas. Biroz kutib, qaytadan urinib "
                             "koʻring.",
                       "en": "Too many photos: without signing in, no more than {n} photos per hour. Please wait "
                             "and try again."},
    "ph_dims_unknown": {"ru": "не удалось прочитать размеры картинки — пришлите другой снимок",
                        "uz": "rasm oʻlchamlarini oʻqib boʻlmadi — boshqa surat yuboring",
                        "en": "could not read the image size — send another picture"},
    "ph_too_many_px": {"ru": "картинка слишком большая: {w}×{h} точек, больше {mp} Мп — уменьшите снимок",
                       "uz": "rasm juda katta: {w}×{h} nuqta, {mp} Mp dan koʻp — suratni kichraytiring",
                       "en": "image too large: {w}×{h} pixels, over {mp} MP — reduce the picture"},
    "ph_pdf_pages": {"ru": "в PDF больше {n} страниц — пришлите только нужные страницы",
                     "uz": "PDF da {n} sahifadan koʻp — faqat kerakli sahifalarni yuboring",
                     "en": "the PDF has more than {n} pages — send only the pages you need"},
    "ph_pdf_bad": {"ru": "PDF не открывается или защищён паролем", "uz": "PDF ochilmaydi yoki parol bilan himoyalangan",
                   "en": "the PDF cannot be opened or is password-protected"},
    "ph_not_sent": {"ru": "Модели не показаны файлы № {files}: вместе с остальными они больше {mb} МБ даже после "
                          "сжатия. Их содержимое не распознано — проверьте вручную или загрузите отдельно.",
                    "uz": "Modelga {files}-fayllar koʻrsatilmadi: siqilgandan keyin ham boshqalar bilan birga {mb} MB "
                          "dan katta. Ularning mazmuni aniqlanmadi — qoʻlda tekshiring yoki alohida yuklang.",
                    "en": "Files No. {files} were not shown to the model: together with the others they exceed "
                          "{mb} MB even after compression. They were not recognised — check them manually or "
                          "upload them separately."},
    "ai_timeout": {"ru": "языковая модель не ответила за {sec} с", "uz": "til modeli {sec} soniyada javob bermadi",
                   "en": "the language model did not answer within {sec} s"},
    "ai_busy": {"ru": "исчерпан общий лимит распознаваний на сервере ({n} в час) — попробуйте позже",
                "uz": "serverdagi umumiy aniqlash limiti tugadi (soatiga {n} ta) — keyinroq urinib koʻring",
                "en": "the server-wide recognition limit ({n} per hour) is used up — try again later"},
    "ai_error": {"ru": "ошибка при обращении к языковой модели", "uz": "til modeliga murojaatda xato",
                 "en": "error when calling the language model"},
    "multi_class_note": {"ru": "Продукт относится к нескольким классам ({classes}); в лёгкой версии считается по "
                               "ставке продукта, разбор по частям отложен.",
                         "uz": "Mahsulot bir nechta klassga tegishli ({classes}); yengil versiyada mahsulot tarifi "
                               "boʻyicha hisoblanadi, qismlarga ajratish keyinga qoldirilgan.",
                         "en": "The product belongs to several classes ({classes}); the light version prices it at "
                               "the product rate, the split by parts is postponed."},

    # ---------- /act/{id}/send ----------
    "send_ok": {"ru": "Акт отправлен в чат с ботом", "uz": "Dalolatnoma bot bilan chatga yuborildi",
                "en": "The report has been sent to your chat with the bot"},
    "send_no_tg": {"ru": "Отправка ботом работает только в Telegram: откройте приложение в Telegram или скачайте "
                         "акт на компьютере",
                   "uz": "Bot orqali yuborish faqat Telegramda ishlaydi: ilovani Telegramda oching yoki "
                         "dalolatnomani kompyuterda yuklab oling",
                   "en": "Sending via the bot works only in Telegram: open the app in Telegram or download the "
                         "report on a computer"},
    "send_bad_init": {"ru": "Не удалось подтвердить вход через Telegram — откройте приложение заново",
                      "uz": "Telegram orqali kirishni tasdiqlab boʻlmadi — ilovani qaytadan oching",
                      "en": "Could not confirm the Telegram sign-in — reopen the app"},
    "send_bot_off": {"ru": "Бот не подключён — скачайте акт на компьютере",
                     "uz": "Bot ulanmagan — dalolatnomani kompyuterda yuklab oling",
                     "en": "The bot is not connected — download the report on a computer"},
    "send_limit": {"ru": "Не больше {n} отправок в час — подождите немного и повторите",
                   "uz": "Soatiga {n} tadan koʻp yuborib boʻlmaydi — biroz kutib, qaytadan urinib koʻring",
                   "en": "No more than {n} sends per hour — please wait and try again"},
    "send_failed": {"ru": "Telegram не принял файл — попробуйте позже или скачайте акт на компьютере",
                    "uz": "Telegram faylni qabul qilmadi — keyinroq urinib koʻring yoki kompyuterda yuklab oling",
                    "en": "Telegram did not accept the file — try later or download the report on a computer"},
    "send_start_bot": {"ru": "Бот не может написать вам первым: откройте чат с ботом, нажмите «Start» и повторите",
                       "uz": "Bot sizga birinchi boʻlib yoza olmaydi: bot bilan chatni oching, «Start» ni bosing va "
                             "qaytadan urinib koʻring",
                       "en": "The bot cannot message you first: open the chat with the bot, press Start and try "
                             "again"},
    "send_format": {"ru": "Формат — docx или pdf", "uz": "Format — docx yoki pdf", "en": "Format must be docx or pdf"},
    "send_caption": {"ru": "Сюрвейерский акт № {number}", "uz": "Syurveyer dalolatnomasi № {number}",
                     "en": "Surveyor's report No. {number}"},
    "session_not_found": {"ru": "Загрузка фото не найдена или её срок (24 часа) истёк — акт собран без неё",
                          "uz": "Suratlar yuklamasi topilmadi yoki muddati (24 soat) tugagan — dalolatnoma usiz tuzildi",
                          "en": "Photo upload not found or expired (24 hours) — the report was built without it"},
}

FIELD_LABELS = {
    "object_type": {"ru": "Тип объекта", "uz": "Obyekt turi", "en": "Object type"},
    "class_hint": {"ru": "Подсказка класса", "uz": "Klass boʻyicha taxmin", "en": "Class hint"},
    "brand": {"ru": "Марка", "uz": "Marka", "en": "Make"},
    "model": {"ru": "Модель", "uz": "Model", "en": "Model"},
    "manufacture_date": {"ru": "Дата изготовления", "uz": "Ishlab chiqarilgan sana", "en": "Date of manufacture"},
    "year": {"ru": "Год выпуска", "uz": "Ishlab chiqarilgan yil", "en": "Year of manufacture"},
    "serial_no": {"ru": "Заводской (серийный) номер", "uz": "Zavod (seriya) raqami", "en": "Serial number"},
    "manufacturer": {"ru": "Производитель", "uz": "Ishlab chiqaruvchi", "en": "Manufacturer"},
    "engine_no": {"ru": "Номер двигателя", "uz": "Dvigatel raqami", "en": "Engine number"},
    "engine_model": {"ru": "Модель двигателя", "uz": "Dvigatel modeli", "en": "Engine model"},
    "engine_power": {"ru": "Мощность двигателя", "uz": "Dvigatel quvvati", "en": "Engine power"},
    "curb_mass": {"ru": "Снаряжённая масса", "uz": "Jihozlangan massa", "en": "Curb weight"},
    "payload": {"ru": "Грузоподъёмность", "uz": "Yuk koʻtarish quvvati", "en": "Lifting capacity"},
    "dimensions": {"ru": "Габариты", "uz": "Gabarit oʻlchamlari", "en": "Dimensions"},
    "color": {"ru": "Цвет", "uz": "Rangi", "en": "Colour"},
    "mileage": {"ru": "Пробег / моточасы", "uz": "Yurgan masofa / motosoat", "en": "Mileage / engine hours"},
    "location": {"ru": "Место эксплуатации", "uz": "Foydalanish joyi", "en": "Place of operation"},
}

SOURCE_LABELS = {
    "photo": {"ru": "с фото объекта", "uz": "obyekt suratidan", "en": "from the object photo"},
    "plate": {"ru": "с заводской таблички", "uz": "zavod lavhachasidan", "en": "from the nameplate"},
    "document": {"ru": "из документа", "uz": "hujjatdan", "en": "from the document"},
    "marking": {"ru": "с маркировки на кузове", "uz": "korpusdagi yozuvdan", "en": "from the body marking"},
    "input": {"ru": "введено сотрудником", "uz": "xodim kiritgan", "en": "entered by staff"},
}
# в строке расхождения: «на табличке 36 170 кг, в документе 38 600 кг»
SOURCE_IN = {
    "photo": {"ru": "на фото", "uz": "suratda", "en": "on the photo"},
    "plate": {"ru": "на табличке", "uz": "lavhachada", "en": "on the nameplate"},
    "document": {"ru": "в документе", "uz": "hujjatda", "en": "in the document"},
    "marking": {"ru": "на маркировке", "uz": "yozuvda", "en": "on the marking"},
    "input": {"ru": "во вводе сотрудника", "uz": "xodim kiritganida", "en": "as entered by staff"},
}

VIEW_LABELS = {
    "front": {"ru": "спереди", "uz": "old tomondan", "en": "front"},
    "back": {"ru": "сзади", "uz": "orqa tomondan", "en": "rear"},
    "left": {"ru": "левый борт", "uz": "chap tomoni", "en": "left side"},
    "right": {"ru": "правый борт", "uz": "oʻng tomoni", "en": "right side"},
    "plate": {"ru": "заводская табличка", "uz": "zavod lavhachasi", "en": "nameplate"},
    "odometer": {"ru": "счётчик пробега или моточасов", "uz": "yurgan masofa yoki motosoat hisoblagichi",
                 "en": "odometer or hour meter"},
    "document": {"ru": "снимок документа", "uz": "hujjat surati", "en": "document image"},
    "interior": {"ru": "внутри", "uz": "ichki koʻrinish", "en": "interior"},
    "facade": {"ru": "фасад", "uz": "fasad", "en": "facade"},
    "roof": {"ru": "кровля", "uz": "tom", "en": "roof"},
    "electrical": {"ru": "электрощит", "uz": "elektr shiti", "en": "electrical panel"},
    "fire_safety": {"ru": "средства пожаротушения", "uz": "yongʻin oʻchirish vositalari", "en": "fire-fighting equipment"},
    "general": {"ru": "общий вид", "uz": "umumiy koʻrinish", "en": "general view"},
    "installation": {"ru": "место установки", "uz": "oʻrnatilgan joy", "en": "installation site"},
    "packaging": {"ru": "упаковка", "uz": "qadoq", "en": "packaging"},
    "marking": {"ru": "маркировка", "uz": "markirovka", "en": "marking"},
    "transport": {"ru": "транспорт", "uz": "transport vositasi", "en": "transport"},
    "other": {"ru": "другое", "uz": "boshqa", "en": "other"},
}

# ссылки на нормы: в данных хранится русское написание, в тексте — на языке акта
LEGAL_REFS = {
    "ГК РУз, ст. 936": {"ru": "ГК РУз, ст. 936", "uz": "OʻzR Fuqarolik kodeksi, 936-modda",
                        "en": "Civil Code of Uzbekistan, Art. 936"},
    "ГК РУз, ст. 938": {"ru": "ГК РУз, ст. 938", "uz": "OʻzR Fuqarolik kodeksi, 938-modda",
                        "en": "Civil Code of Uzbekistan, Art. 938"},
}

LOCATION_LABELS = {
    "open_area": {"ru": "открытая площадка", "uz": "ochiq maydon", "en": "open yard"},
    "construction": {"ru": "строительная площадка", "uz": "qurilish maydoni", "en": "construction site"},
    "port": {"ru": "порт", "uz": "port", "en": "port"},
    "guarded": {"ru": "охраняемая территория", "uz": "qoʻriqlanadigan hudud", "en": "guarded area"},
    "closed_storage": {"ru": "закрытое хранение", "uz": "yopiq saqlash", "en": "indoor storage"},
    "other": {"ru": "другое место", "uz": "boshqa joy", "en": "other place"},
}

LEVEL_LABELS = {
    "low": {"ru": "низкий", "uz": "past", "en": "low"},
    "moderate": {"ru": "умеренный", "uz": "oʻrtacha", "en": "moderate"},
    "high": {"ru": "высокий", "uz": "yuqori", "en": "high"},
}

GROUP_LABELS = {
    "special": {"ru": "спецтехника", "uz": "maxsus texnika", "en": "special machinery"},
    "vehicle": {"ru": "транспорт", "uz": "transport", "en": "vehicle"},
    "property": {"ru": "здание, помещение", "uz": "bino, xona", "en": "building, premises"},
    "equipment": {"ru": "оборудование", "uz": "uskuna", "en": "equipment"},
    "cargo": {"ru": "груз", "uz": "yuk", "en": "cargo"},
    "liability": {"ru": "ответственность", "uz": "javobgarlik", "en": "liability"},
    "other": {"ru": "прочее", "uz": "boshqa", "en": "other"},
}

# вид объекта (подсказка модели) → тип объекта справочника базовых ставок; подписи — на трёх языках
OBJECT_KINDS = {
    "truck_crane": ("Спецтехника — автокран", {"ru": "автокран", "uz": "avtokran", "en": "truck crane"}),
    "crawler_crane": ("Спецтехника — кран гусеничный", {"ru": "гусеничный кран", "uz": "gusenitsali kran",
                                                        "en": "crawler crane"}),
    "excavator": ("Спецтехника — экскаватор", {"ru": "экскаватор", "uz": "ekskavator", "en": "excavator"}),
    "backhoe_loader": ("Спецтехника — экскаватор-погрузчик", {"ru": "экскаватор-погрузчик",
                                                              "uz": "ekskavator-yuklagich", "en": "backhoe loader"}),
    "bulldozer": ("Спецтехника — бульдозер", {"ru": "бульдозер", "uz": "buldozer", "en": "bulldozer"}),
    "wheel_loader": ("Спецтехника — погрузчик фронтальный", {"ru": "фронтальный погрузчик",
                                                             "uz": "frontal yuklagich", "en": "wheel loader"}),
    "forklift": ("Спецтехника — погрузчик вилочный", {"ru": "вилочный погрузчик", "uz": "vilkali yuklagich",
                                                      "en": "forklift"}),
    "telehandler": ("Спецтехника — телескопический погрузчик", {"ru": "телескопический погрузчик",
                                                                "uz": "teleskopik yuklagich", "en": "telehandler"}),
    "aerial_platform": ("Спецтехника — автовышка", {"ru": "автовышка", "uz": "avtominora",
                                                    "en": "aerial work platform"}),
    "concrete_pump": ("Спецтехника — бетононасос", {"ru": "бетононасос", "uz": "beton nasos",
                                                    "en": "concrete pump"}),
    "concrete_mixer": ("Спецтехника — автобетоносмеситель", {"ru": "автобетоносмеситель",
                                                             "uz": "avtobetonaralashtirgich",
                                                             "en": "truck mixer"}),
    "drilling_rig": ("Спецтехника — буровая установка", {"ru": "буровая установка", "uz": "burgʻulash qurilmasi",
                                                         "en": "drilling rig"}),
    "road_machinery": ("Спецтехника — дорожная (каток, грейдер, асфальтоукладчик)",
                       {"ru": "дорожная техника", "uz": "yoʻl texnikasi", "en": "road machinery"}),
    "tractor": ("Спецтехника — трактор", {"ru": "трактор", "uz": "traktor", "en": "tractor"}),
    "combine": ("Спецтехника — комбайн", {"ru": "комбайн", "uz": "kombayn", "en": "combine harvester"}),
    "special_other": ("Спецтехника", {"ru": "спецтехника", "uz": "maxsus texnika", "en": "special machinery"}),
    "trailer": ("Прицеп и полуприцеп", {"ru": "прицеп", "uz": "tirkama", "en": "trailer"}),
    "car": ("Легковой", {"ru": "легковой автомобиль", "uz": "yengil avtomobil", "en": "passenger car"}),
    "truck": ("Грузовой", {"ru": "грузовой автомобиль", "uz": "yuk avtomobili", "en": "truck"}),
    "electric_car": ("Электромобиль", {"ru": "электромобиль", "uz": "elektromobil", "en": "electric car"}),
    "warehouse": ("Склад", {"ru": "склад", "uz": "ombor", "en": "warehouse"}),
    "shop": ("Магазин", {"ru": "магазин", "uz": "doʻkon", "en": "shop"}),
    "production": ("Производство", {"ru": "производственное здание", "uz": "ishlab chiqarish binosi",
                                    "en": "production building"}),
    "office": ("Офис", {"ru": "офис", "uz": "ofis", "en": "office"}),
    "dwelling": ("Жильё", {"ru": "жильё", "uz": "turar joy", "en": "dwelling"}),
    "hotel": ("Гостиница", {"ru": "гостиница", "uz": "mehmonxona", "en": "hotel"}),
    "equipment": ("Машины и оборудование", {"ru": "машины и оборудование", "uz": "mashina va uskunalar",
                                            "en": "machinery and equipment"}),
    "cargo": (None, {"ru": "груз", "uz": "yuk", "en": "cargo"}),
    "other": (None, {"ru": "прочее", "uz": "boshqa", "en": "other"}),
}
