"""
Проверка db/schema.sql и кода на особенности SQLite, которые придётся поправить
при переносе базы на PostgreSQL.

Запуск:  sandbox\\.venv\\Scripts\\python.exe tools/schema_check.py
Из сервера: GET /deploy/schema-check (страница /admin/deploy).

Ничего не меняет — только читает файлы и печатает список.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "db" / "schema.sql"
CODE_DIRS = (ROOT / "app", ROOT / "tools")

ERR, WARN = "ошибка", "предупреждение"

# (уровень, регулярное выражение, что не так и что делать)
SCHEMA_RULES = [
    (ERR, r"\bAUTOINCREMENT\b",
     "AUTOINCREMENT в PostgreSQL не существует: заменить на GENERATED BY DEFAULT AS IDENTITY (или SERIAL)"),
    (ERR, r"INTEGER\s+PRIMARY\s+KEY(?!\s+REFERENCES)(?!\s*,\s*\w)",
     "«INTEGER PRIMARY KEY» в SQLite сам нумерует строки, в PostgreSQL — нет: "
     "заменить на «id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY»"),
    (ERR, r"datetime\(\s*'now'|date\(\s*'now'|strftime\(",
     "функции SQLite datetime('now')/date('now')/strftime(): в PostgreSQL — now(), current_date, to_char()"),
    (ERR, r"INSERT\s+OR\s+(REPLACE|IGNORE)",
     "«INSERT OR REPLACE/IGNORE» — синтаксис SQLite: в PostgreSQL «INSERT ... ON CONFLICT (...) DO UPDATE/NOTHING»"),
    (WARN, r"\bWITHOUT\s+ROWID\b", "WITHOUT ROWID — только SQLite, при переносе убрать"),
    (WARN, r"\bPRAGMA\b", "PRAGMA — только SQLite"),
    (WARN, r"\bGLOB\b|\bLIKE\s+'%'\s*ESCAPE", "GLOB и особенности LIKE различаются: проверить вручную"),
    (WARN, r"\|\|\s*'", "склейка строк через || работает в обоих, но при NULL результат NULL — проверить"),
]

CODE_RULES = [
    (ERR, r"sqlite3\.", "прямое обращение к sqlite3: доступ к базе должен идти через app/db.py"),
    (ERR, r"INSERT\s+OR\s+(REPLACE|IGNORE)", "«INSERT OR REPLACE/IGNORE» — синтаксис SQLite (см. выше)"),
    (ERR, r"datetime\(\s*'now'|strftime\(", "функции даты SQLite в SQL-запросе"),
    (WARN, r"last_insert_rowid\(\)|\.lastrowid",
     "lastrowid — в PostgreSQL нужен «INSERT ... RETURNING id»"),
    (WARN, r"\bGROUP_CONCAT\s*\(", "GROUP_CONCAT → в PostgreSQL string_agg()"),
]


def _lines(text: str):
    return list(enumerate(text.splitlines(), 1))


def check_schema() -> list:
    out = []
    if not SCHEMA.exists():
        return [{"level": ERR, "text": "Файл db/schema.sql не найден"}]
    text = SCHEMA.read_text(encoding="utf-8")
    for level, rx, msg in SCHEMA_RULES:
        hits = [n for n, ln in _lines(text) if not ln.strip().startswith("--") and re.search(rx, ln, re.I)]
        if hits:
            where = ", ".join(str(h) for h in hits[:8]) + (" и ещё %d" % (len(hits) - 8) if len(hits) > 8 else "")
            out.append({"level": level, "text": f"db/schema.sql (строки {where}): {msg}",
                        "count": len(hits)})
    # колонки без типа: «name,» или «name NOT NULL» без типа данных
    no_type = []
    for n, ln in _lines(text):
        s = ln.strip()
        if s.startswith("--") or s.upper().startswith(("CREATE", "PRIMARY", "UNIQUE", "FOREIGN", "REFERENCES", ")")):
            continue
        if re.match(r"^[a-z_][a-z0-9_]*\s*(,|\))", s):
            no_type.append(n)
    if no_type:
        out.append({"level": ERR, "count": len(no_type),
                    "text": "db/schema.sql: колонки без типа данных (строки %s) — SQLite это допускает, "
                            "PostgreSQL требует тип" % ", ".join(map(str, no_type[:8]))})
    # даты и логические значения хранятся текстом/числом
    if re.search(r"TEXT[^\n]*--[^\n]*(дата|ISO)", text, re.I) or "created_at    TEXT" in text:
        out.append({"level": WARN, "count": 0,
                    "text": "даты хранятся как TEXT (ISO-строки): при переносе перевести в TIMESTAMP, "
                            "иначе сортировка и сравнение дат будут работать как со строками"})
    if re.search(r"INTEGER[^\n]*DEFAULT\s+[01]\b", text):
        out.append({"level": WARN, "count": 0,
                    "text": "логические признаки хранятся как INTEGER 0/1: в PostgreSQL удобнее BOOLEAN "
                            "(иначе «WHERE done = 1» придётся переписывать)"})
    return out


def check_code() -> list:
    out = []
    for folder in CODE_DIRS:
        for f in sorted(folder.glob("*.py")):
            if f.name in ("schema_check.py", "db.py"):    # сам чек и слой доступа к базе — не в счёт
                continue
            try:
                text = f.read_text(encoding="utf-8")
            except Exception:
                continue
            for level, rx, msg in CODE_RULES:
                hits = [n for n, ln in _lines(text) if re.search(rx, ln)]
                if hits:
                    out.append({"level": level, "count": len(hits),
                                "text": f"{f.parent.name}/{f.name} (строк: {len(hits)}): {msg}"})
    # плейсхолдеры: sqlite3 понимает «?», psycopg — «%s»
    out.append({"level": ERR, "count": 0,
                "text": "во всех запросах параметры подставляются через «?» — в PostgreSQL (psycopg) "
                        "нужен «%s»: при переносе это делается один раз в app/db.py (обёртка execute), "
                        "а не правкой каждого запроса"})
    out.append({"level": WARN, "count": 0,
                "text": "конкурентная запись: SQLite блокирует файл целиком. На PostgreSQL это уйдёт, "
                        "но текущие «сначала DELETE, потом INSERT» лучше заменить на ON CONFLICT"})
    return out


def check() -> dict:
    problems = check_schema() + check_code()
    ok = not any(p["level"] == ERR for p in problems)
    return {"ok": ok, "problems": problems,
            "summary": "Схема переносится на PostgreSQL, но %d пунктов требуют правки" % len(problems)}


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    res = check()
    print("Проверка схемы на переносимость в PostgreSQL")
    print("-" * 70)
    for p in res["problems"]:
        print(f"[{p['level']}] {p['text']}")
    print("-" * 70)
    print(res["summary"])
